syntax = "proto3";
package hearth.node.grpc;
option java_package = "tech.hearth.api.grpc";
option csharp_namespace = "Waves.Node.Grpc";
option go_package = "github.com/wavesplatform/gowaves/pkg/grpc/generated/hearth/node/grpc";

import "hearth/recipient.proto";
import "hearth/transaction.proto";
import "hearth/transaction_state_snapshot.proto";

service TransactionsApi {
    rpc GetTransactions (TransactionsRequest) returns (stream TransactionResponse);
    rpc GetTransactionSnapshots (TransactionSnapshotsRequest) returns (stream TransactionSnapshotResponse);
    rpc GetStatuses (TransactionsByIdRequest) returns (stream TransactionStatus);
    rpc GetUnconfirmed (TransactionsRequest) returns (stream TransactionResponse);

    rpc Sign (SignRequest) returns (SignedTransaction);
    rpc Broadcast (SignedTransaction) returns (SignedTransaction);
}

enum ApplicationStatus {
    UNKNOWN = 0;
    SUCCEEDED = 1;
    SCRIPT_EXECUTION_FAILED = 2;
    ELIDED = 3;
}

message TransactionStatus {
    enum Status {
        NOT_EXISTS = 0;
        UNCONFIRMED = 1;
        CONFIRMED = 2;
    }

    bytes id = 1;
    Status status = 2;
    int64 height = 3;
    ApplicationStatus application_status = 4;
}

message TransactionResponse {
    bytes id = 1;
    int64 height = 2;
    SignedTransaction transaction = 3;
    ApplicationStatus application_status = 4;
}

message TransactionsRequest {
    bytes sender = 1;
    Recipient recipient = 2;
    repeated bytes transaction_ids = 3;
}

message TransactionSnapshotResponse {
    bytes id = 1;
    TransactionStateSnapshot snapshot = 2;
}

message TransactionSnapshotsRequest {
    repeated bytes transaction_ids = 1;
}

message TransactionsByIdRequest {
    repeated bytes transaction_ids = 3;
}

message CalculateFeeResponse {
    bytes asset_id = 1;
    uint64 amount = 2;
}

message SignRequest {
    Transaction transaction = 1;
    bytes signer_public_key = 2;
}

message InvokeScriptResultResponse {
    SignedTransaction transaction = 1;
}
